export const list_of_countries = [
    "México",
    "Albania",
    "Alemania",
    "Argentina",
    "Austria",
    "Belice",
    "Bielorrusia",
    "Bolivia",
    "Bosnia y Herzegovina",
    "Brasil",
    "Bulgaria",
    "Canadá",
    "China",
    "Chipre",
    "Colombia",
    "Costa Rica",
    "Croacia",
    "Cuba",
    "Dinamarca",
    "El Salvador",
    "Estonia",
    "España",
    "Eslovaquia",
    "Eslovenia",
    "Estados Unidos",
    "Finlandia",
    "Francia",
    "Grecia",
    "Guatemala",
    "Guayana Francesa",
    "Guyana",
    "Haití",
    "Honduras",
    "Irlanda",
    "Islandia",
    "Italia",
    "Jamaica",
    "Japón",
    "Kosovo",
    "Letonia",
    "Lituania",
    "Luxemburgo",
    "Macedonia del Norte",
    "Malta",
    "Moldavia",
    "Montenegro",
    "Nicaragua",
    "Noruega",
    "Países Bajos",
    "Panamá",
    "Paraguay",
    "Perú",
    "Polonia",
    "Portugal",
    "Puerto Rico",
    "Reino Unido",
    "República Checa",
    "República Dominicana",
    "Rumania",
    "Rusia",
    "Serbia",
    "Suecia",
    "Surinam",
    "Suiza",
    "Trinidad y Tobago",
    "Turquía",
    "Ucrania",
    "Uruguay",
    "Venezuela"
];
